### ISSUE TITLE
Handle loading done event

### ISSUE THREAD

**Issue by minhkte** [novoda/image-loader#108]
I want to display default ImageView is progressbar. I have try to layout progressbar with imageview then handle event to invisible progressbar as well.
As I know, we can do it in OnImageLoadedListener by override onImageLoaded function to invisible progressbar. But only first time when load from url, it's run, when get from cache, it's not run.
Anyone can give me suggestions about this case.
I really appreciate about that.

**Comment by blundell** [comment]
sorry repo now deprecated
