### ISSUE TITLE
LoaderSettings is too large

### ISSUE THREAD

**Issue by ataulm** [novoda/image-loader#154]
LoaderSettings is too large a class. It contains four main components:

- NetworkManager
- CacheManager
- FileManager
- Loader

Each of these objects query the LoaderSettings for things, and act differently based on the values set in LoaderSettings. Instead, these objects should be constructed with all the information they need to run.

Consequently, LoaderSettings will have just four inputs, instead of the 10+ it has now. It should make the project easier to test in theory too - we will no longer need a LoaderSettings object for testing each component.

Name-wise, it'll then be lame because it's not really a settings object, it's an ImageLoaderManager, and since it'll then do squat, these four things could compose the ImageLoader itself, bypassing the need for a "settings" object?

![](http://i.imgur.com/S25EO.gif)

*I'm not saying to delete the class, rather deprecate it, and add alternatives

**Comment by friedger** [comment]
`LoaderSettings` has been removed. Settings can now be aggregated in a `Factory` like https://github.com/novoda/image-loader/blob/develop/core/src/main/java/com/novoda/pxfetcher/RetrieverFactory.java
