### ISSUE TITLE
Skia decoder return false

### ISSUE THREAD

**Issue by CedrickFlocon** [novoda/image-loader#165]
Hello, 

Some time i got this log when i try to load image in a GridView (via an ArrayAdapter) : 
05-02 ... /com.x.y.debug D/skia﹕ --- decoder->decode returned false
05-02 ... /com.x.y.debug D/skia﹕ --- SkImageDecoder::Factory returned null

One Image will not be displayed in my GridView.
If i force a reload(scroll down then up) the image will be correctly shown.
Can you detect this state and perform an auto retry ? 

ImageLoader settings:

LoaderSettings settings = new LoaderSettings.SettingsBuilder()
                                                    .withDisconnectOnEveryCall(true)
                                                    .withCacheManager(new LruBitmapCache(this)).build(this);

Platforme : 

Nexus 5 and nexus 4
android : 4.4.2
com.novoda.imageloader:imageloader-core:1.6.1

**Comment by friedger** [comment]
This could be related to low memory.

In version 2.0, a retry could be executed in the Callback.onResult(Failure ko)
