### ISSUE TITLE
Improve the relationship between a BitmapProcessor and a Retriever

### ISSUE THREAD

**Issue by xrigau** [novoda/image-loader#183]
https://github.com/novoda/ImageLoader/blob/develop/pxfetcher/src/main/java/com/novoda/pxfetcher/BitmapProcessor.java

@mr-archano wrote:

 > This component is meant to be the companion for a retriever, and is meant to be executed to apply any kind of elaboration on the retrieved Bitmap. That is not only transformations as cropping, scaling, etc but basically a real hook in the retriever-based architecture.

And he also worte:

 > This processor can be used to store the given bitmap in a memory cache. It's supposed to work along with a retriever (although not limited to that): the retriever just retrieves a Bitmap, and it's not (and should not IMO) its responsibility to save the bmp into the memory cache. That's when this class comes in handy

On: https://github.com/novoda/ImageLoader/blob/develop/pxfetcher/src/main/java/com/novoda/pxfetcher/CacheBitmapProcessor.java

**Comment by friedger** [comment]
@mr-archano Your comments are stored in the https://github.com/novoda/image-loader/wiki/Components-(since--2.0)
