### ISSUE TITLE
OnImageLoadedListener and Placeholder

### ISSUE THREAD

**Issue by jarofgreen** [novoda/image-loader#201]
I'm using Novoda 1.6.1 and running into problems with OnImageLoadedListener

	protected OnImageLoadedListener onImageLoadedListener = new OnImageLoadedListener() {
		@Override
		public void onImageLoaded(ImageView imageView) {
			if (imageView.getId() == R.id.latest_entry) {				
				Bitmap bitmap = ((BitmapDrawable) imageView.getDrawable()).getBitmap();
				((ImageView)findViewById(R.id.latest_entry_2)).setImageBitmap(bitmap);
			}
		}
	};

R.id.latest_entry is an ImageView that has been loaded by the library.

For this  simple example, all I want to do is get the Bitmap and set it to another ImageView. (I am carefully using a BitMap as what I actually want to do is apply a filter using ScriptIntrinsicBlur then put it back, so it has to be Bitmaps)

But it doesn't work - the image loads fine into R.id.latest_entry, but the image that shows in R.id.latest_entry_2 is in fact the placeholder that is set here:

		imageTagFactory = ImageTagFactory.newInstance(this, R.drawable.image_to_download_from_web_placeholder);

Any ideas on how I can get the actual image?

Alternatively, I notice that 2.0 is out soon - when is it out? Should I just be using this? I'm not sure the public code is complete for this - the Readme refers to ImageManager class but that doesn't seem to be in the repo?

Also, it strikes me that a better than setting the Bitmap, getting the Bitmap, applying ScriptIntrinsicBlur, then putting the Bitmap back would be if in the image Tag, you could specify a filter class. Is this a feature that sounds interesting?

**Comment by friedger** [comment]
In 2.0 this can be implemented as an [ImageSetter](https://github.com/novoda/image-loader/blob/develop/core/src/main/java/com/novoda/pxfetcher/ImageSetter.java)
